enum ErrorCode {
  DATASET_EMPTY = 'DATASET_EMPTY',
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
  DATASET_NOT_FOUND = 'DATASET_NOT_FOUND',
  SCANNING_INCOMPLETE = 'SCANNING_INCOMPLETE',
}

export default ErrorCode;
