enum ErrorCode {
  DEAL_SIZE_NOT_ALLOWED = 'DEAL_SIZE_NOT_ALLOWED',
  PATH_NOT_ACCESSIBLE = 'PATH_NOT_ACCESSIBLE',
  DATASET_NAME_CONFLICT = 'DATASET_NAME_CONFLICT',
  DATASET_NOT_FOUND = 'DATASET_NOT_FOUND',
  CANNOT_CHANGE_STATE_IF_SCANNING_NOT_COMPLETE = 'CANNOT_CHANGE_STATE_IF_SCANNING_NOT_COMPLETE',
  DATASET_GENERATION_REQUEST_NOT_FOUND = 'DATASET_GENERATION_REQUEST_NOT_FOUND',
  CHANGE_STATE_INVALID = 'CHANGE_STATE_INVALID',
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
}

export default ErrorCode;
