enum ErrorCode {
  DEAL_SIZE_NOT_ALLOWED = 'DEAL_SIZE_NOT_ALLOWED',
  PATH_NOT_ACCESSIBLE = 'PATH_NOT_ACCESSIBLE',
  TMPDIR_MISSING_FOR_S3 = 'TMPDIR_MISSING_FOR_S3',
  DATASET_NAME_CONFLICT = 'DATASET_NAME_CONFLICT',
  DATASET_NOT_FOUND = 'DATASET_NOT_FOUND',
  CANNOT_CHANGE_STATE_IF_SCANNING_NOT_COMPLETE = 'CANNOT_CHANGE_STATE_IF_SCANNING_NOT_COMPLETE',
  DATASET_GENERATION_REQUEST_NOT_FOUND = 'DATASET_GENERATION_REQUEST_NOT_FOUND',
  ACTION_INVALID = 'ACTION_INVALID',
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
  MIN_RATIO_INVALID = 'MIN_RATIO_INVALID',
  MAX_RATIO_INVALID = 'MAX_RATIO_INVALID',
  GENERATION_NOT_COMPLETED = 'GENERATION_NOT_COMPLETED',
}

export default ErrorCode;
