enum ErrorCode {
  DATASET_NAME_CONFLICT = 'DATASET_NAME_CONFLICT',
  DATASET_NOT_FOUND = 'DATASET_NOT_FOUND',
  CHANGE_STATE_INVALID = 'CHANGE_STATE_INVALID',
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export default ErrorCode;
