import DealState from '../../common/model/DealState';

export default interface GetReplicationDetailsResponse {
    id: string,
    datasetId: string,
    storageProviders: string,
    client: string,
    replica: number,
    urlPrefix: string,
    maxPrice: number,
    maxNumberOfDeals: number,
    isVerfied: string,
    startDelay: number,
    duration: number,
    isOffline: string,
    status: 'active' | 'paused' | 'completed' | 'error',
    cronSchedule?: string,
    cronMaxDeals?: number,
    cronMaxPendingDeals?: number,
    fileListPath?: string,
    notes?: string,
    csvOutputDir?: string,
    isForced: boolean,
    dealsTotal?: number,
    dealsProposed?: number,
    dealsPublished?: number,
    dealsActive?: number,
    dealsProposalExpired?: number,
    dealsExpired?: number,
    dealsSlashed?: number,
    dealsError?: number,
    deals?: Array<DealState>
  }
